# Generated by Django 6.0.7 on 2026-08-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Boy'), ('F', 'Girl'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
