# Generated by Django 6.0.7 on 2026-08-28 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_secure_otp_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('class', 'Live Class'), ('listening', 'Listening Session'), ('reading', 'Reading Story'), ('announcement', 'Announcement'), ('awareness', 'Awareness / Tip'), ('update', 'Update')], default='announcement', max_length=20)),
                ('teacher_name', models.CharField(blank=True, help_text='Name of the teacher who added this notification or session', max_length=120, null=True)),
                ('link', models.CharField(blank=True, help_text='Destination route, e.g. /live-class or /listening or /reading', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
