# Generated by Django 6.0.7 on 2026-08-04 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Speaking Time, Listen & Learn', max_length=150)),
                ('lesson', models.CharField(help_text='e.g., Lesson 4: My Favourite Animal', max_length=255)),
                ('teacher_name', models.CharField(help_text='e.g., Ms. Meera', max_length=100)),
                ('duration_minutes', models.PositiveIntegerField(default=20, help_text='Duration in minutes')),
                ('class_time', models.TimeField(help_text='Scheduled class time')),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_live', models.BooleanField(default=False, help_text='Mark if this class is currently live')),
                ('is_today', models.BooleanField(default=True, help_text="Display on Today's Class section")),
                ('tint_color', models.CharField(choices=[('#FF4D8D', 'Pink'), ('#3B9CF2', 'Blue'), ('#FFA531', 'Orange'), ('#9B6BE0', 'Purple')], default='#FF4D8D', help_text='Border and theme accent color', max_length=10)),
                ('thumbnail', models.ImageField(blank=True, help_text='Upload custom teacher/class thumbnail image', null=True, upload_to='live_classes/thumbnails/')),
                ('meeting_link', models.URLField(blank=True, help_text='URL to join the live session (Zoom/Meet)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'ordering': ['class_time', '-is_live'],
            },
        ),
    ]
