# Generated by Django 6.0.7 on 2026-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='class_date',
            field=models.DateField(blank=True, help_text='Scheduled class date', null=True),
        ),
    ]
