# Generated by Django 6.0.7 on 2026-08-07 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_session', '0002_liveclass_class_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveclass',
            options={'ordering': ['class_time'], 'verbose_name': 'Live Class'},
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='is_today',
        ),
        migrations.AddField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('scheduled', '🟡 Scheduled'), ('live', '🔴 In Progress (Live)'), ('completed', '🟢 Completed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='live_classes/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='tint_color',
            field=models.CharField(choices=[('#FF4D8D', 'Pink'), ('#3B9CF2', 'Blue'), ('#FFA531', 'Orange'), ('#9B6BE0', 'Purple')], default='#FF4D8D', max_length=10),
        ),
    ]
